******************************************
The equivalent circuit of the electrode
******************************************

In the theory handout, we discussed how we can represent an electrode as a circuit containing a resistance and a capacitance. We’ll now build this equivalent circuit in the simulator. We will use this to examine the relationship between |Vec| and |Vin|, i.e., how faithfully the electrode transfers the signal from our neuron to our recording system.

A.	Use the simulator to build the equivalent circuit of the electrode as shown below:

.. image:: ../_static/images/EEA/eea_fig-9.png
  :align: center

Here are some values to use:

*	|Rm|: the DC resistance of the metal electrode wire, 10-100 Ohms.
*	Ce: the electrode tip capacitance, generated by the double layer generated around the electrode.  |Ce| ~ 0.2 pF / µm2, so around 10 - 20 pF (if the electrode is unplated)
*	|Re|: electrode tip resistance, in parallel with |Ce|. ~ 10 to 100 MOhm.
*	|Cs| is the input shunt capacitance, due to the capacitance along the insulated portion of the electrode and wire (~50-100 pF).

B.	We can’t see much without an input signal. Add a 1KHz alternating voltage supply to mimic the signal coming from your cell.
C.	Visualise the 1KHz input in the scope.
D.	Add a new scope with the signal as seen by the end of the electrode wire. This allows us to compare the signal at the extracellular fluid (|Vec|) with what we’re getting out of our electrode (|Vin|). How are they different?


The DC resistance of the wire, |Rm|, is very low, so the voltage drop over it is tiny. We can treat this as a short circuit.

E.	Stop the simulation and remove this resistance. You should see that this hardly influences the relationship between the input and output of your electrode. We can therefore simplify our equivalent circuit by leaving this resistance out.
F.	|Re| and |Ce| are in parallel, and because |Re| has such a high resistance, little current will actually travel over this resistor: |Ce| will have a much bigger effect on the circuit. Simplify the circuit even further by deleting |Re|.

We’re left with our electrode and the long wire represented by two capacitors (|Ce| and |Cs|).
Above, we described a voltage divider made of two (or more) resistors. Capacitors in series can act as a voltage divider too, splitting the input voltage up according to the ratio of resistance (impedance in the case of capacitors) that they provide.

G.	What is the ratio between |Ce| and |Cs| at the moment? How much of our voltage |Vec| is reaching the output of our electrode, |Vin|?  What could we change to get more of our voltage signal reaching the output? Try changing values in the simulator to get a larger amplitude output signal.
